from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from domain.ui_compiler import CompositionManifest, UIPlan, UICompilerArtifactStore

from .project_writer import write_json, write_text


class PageComposer:
    def __init__(self, *, store: UICompilerArtifactStore) -> None:
        self.store = store

    def compose(
        self,
        *,
        run_id: str,
        run_root: Path,
        plan: UIPlan,
        accepted_decisions: dict[str, Any],
        target: dict[str, Any] | None = None,
    ) -> CompositionManifest:
        target = target if isinstance(target, dict) else {}
        source_root = run_root / "composition" / "source"
        source_root.mkdir(parents=True, exist_ok=True)
        imports: list[dict[str, Any]] = []
        for contract in plan.contracts():
            decision = accepted_decisions.get(contract.id)
            accepted_candidate_id = (
                decision.accepted_candidate_id
                if hasattr(decision, "accepted_candidate_id")
                else None
            )
            if not accepted_candidate_id:
                raise ValueError(f"missing accepted bundle for {contract.id}")
            imports.append(
                {
                    "nodeId": contract.id,
                    "candidateId": accepted_candidate_id,
                    "importPath": f"../../accepted/{contract.id}/source/Component",
                }
            )
        slot_mappings = _slot_mappings(plan)
        write_text(source_root / "generated-index.ts", _generated_index(imports))
        write_text(source_root / "App.tsx", _app_source(imports, slot_mappings))
        write_json(
            source_root / "adapters" / "slot-mappings.json",
            {"slotMappings": slot_mappings, "target": target},
        )
        manifest = CompositionManifest(
            run_id=run_id,
            source_root=str(source_root),
            entry=str(target.get("entry") or "src/App.tsx"),
            imports=imports,
            slot_mappings=slot_mappings,
        )
        self.store.save_composition(
            run_id=run_id,
            manifest=manifest.to_dict(),
            report={
                "status": "composed",
                "leafSourceEdited": False,
                "imports": imports,
                "slotMappings": slot_mappings,
            },
        )
        return manifest


def _slot_mappings(plan: UIPlan) -> list[dict[str, Any]]:
    mappings: list[dict[str, Any]] = []
    for contract in plan.contracts():
        for slot in contract.slots:
            if slot.accepts_node_id:
                mappings.append({"parentNodeId": contract.id, "slotId": slot.id, "nodeId": slot.accepts_node_id})
    return mappings


def _generated_index(imports: list[dict[str, Any]]) -> str:
    import_lines = ["// Generated by Rumi recursive UI compiler."]
    entries = ["export const rumiComponents = {"]
    for item in imports:
        symbol = _symbol(str(item["nodeId"]))
        import_lines.append(f"import {symbol} from '{item['importPath']}';")
        entries.append(f"  '{item['nodeId']}': {symbol},")
    entries.append("};")
    return "\n".join([*import_lines, "", *entries])


def _app_source(imports: list[dict[str, Any]], slot_mappings: list[dict[str, Any]]) -> str:
    return "\n".join(
        [
            "import { rumiComponents } from './generated-index';",
            "",
            "export default function App() {",
            f"  const slotMappings = {json.dumps(slot_mappings, ensure_ascii=False)};",
            "  return (",
            "    <main data-rumi-composition=\"recursive-ui\">",
            "      {Object.entries(rumiComponents).map(([nodeId, Component]) => (",
            "        <Component key={nodeId} slotMappings={slotMappings} />",
            "      ))}",
            "    </main>",
            "  );",
            "}",
        ]
    )


def _symbol(node_id: str) -> str:
    return "Component" + "".join(part.capitalize() for part in node_id.split("-"))
