# flow/50_message.flow.yaml
# メッセージ処理パイプライン（公式・ドメイン非依存）
#
# 注意: このFlowはドメイン固有のキー名を知らない
# "message.handler" 等のキーはecosystemのComponentが登録する

flow_version: "2.0"
metadata:
  id: "message"
  priority: 50
  description: "メッセージ処理パイプライン"

defaults:
  fail_soft: true

pipelines:
  # 同期メッセージ処理
  message:
    # ハンドラを呼び出し（何を呼ぶかはInterfaceRegistryに登録されたもの次第）
    - id: "message.handle"
      description: "登録されたメッセージハンドラを呼び出し"
      run:
        handler: "kernel:ir.call"
        args:
          key: "message.handler"
          pass_ctx: true
          store_as: "message_result"
      on_error:
        action: "continue"

    # 結果を出力用に設定
    - id: "message.output"
      description: "結果をoutputに設定"
      run:
        handler: "kernel:ctx.copy"
        args:
          from_key: "message_result"
          to_key: "output"
      on_error:
        action: "continue"

  # ストリーミングメッセージ処理
  message_stream:
    # ストリーミングフラグを設定
    - id: "message_stream.set_flag"
      description: "ストリーミングフラグを設定"
      run:
        handler: "kernel:ctx.set"
        args:
          key: "streaming"
          value: true

    # ストリーミングハンドラを呼び出し
    - id: "message_stream.handle"
      description: "登録されたストリーミングハンドラを呼び出し"
      run:
        handler: "kernel:ir.call"
        args:
          key: "message.handler.stream"
          pass_ctx: true
          store_as: "message_result"
      on_error:
        action: "continue"

    # 結果を出力用に設定
    - id: "message_stream.output"
      description: "結果をoutputに設定"
      run:
        handler: "kernel:ctx.copy"
        args:
          from_key: "message_result"
          to_key: "output"
      on_error:
        action: "continue"
