# @generated by scripts/generate_host_mediator_functions.py
# Source: core_runtime/host_permissions/default_registry.json
# Do not edit by hand; update the registry/generator and rerun with --write.
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _host_mediator import run_host_mediator


def run(context, args):
    return run_host_mediator(
        context,
        args,
        function_id="host_stream_start",
        operation="host.stream.start",
        stream_allowed=True,
    )
