// Generated by tool/generate_defaultspack_mobile_tool_manifest.dart.
// Do not edit by hand.

class DefaultspackToolAgentManifestEntry {
  const DefaultspackToolAgentManifestEntry({
    required this.id,
    required this.description,
    required this.tags,
    required this.aliases,
    required this.inputSchema,
  });

  final String id;
  final String description;
  final List<String> tags;
  final List<String> aliases;
  final Map<String, dynamic> inputSchema;
}

const defaultspackToolAgentManifestCatalog =
    <DefaultspackToolAgentManifestEntry>[
  DefaultspackToolAgentManifestEntry(
    id: "agent_add_instruction",
    description: "Add an instruction to an agent.",
    tags: <String>["agent"],
    aliases: <String>[
      "defaults.agent.add.instruction",
      "defaults.agent.add_instruction",
      "defaultspack.agent.add.instruction",
      "defaultspack.agent.add_instruction"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_approve",
    description: "Approve an agent action.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.approve", "defaultspack.agent.approve"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_cancel",
    description: "Cancel an agent execution.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.cancel", "defaultspack.agent.cancel"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_execute",
    description: "Start an agent execution.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.execute", "defaultspack.agent.execute"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_interrupt_add",
    description: "Add an agent interrupt.",
    tags: <String>["agent"],
    aliases: <String>[
      "defaults.agent.interrupt.add",
      "defaults.agent.interrupt_add",
      "defaultspack.agent.interrupt.add",
      "defaultspack.agent.interrupt_add"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_interrupt_cancel",
    description: "Cancel an agent interrupt.",
    tags: <String>["agent"],
    aliases: <String>[
      "defaults.agent.interrupt.cancel",
      "defaults.agent.interrupt_cancel",
      "defaultspack.agent.interrupt.cancel",
      "defaultspack.agent.interrupt_cancel"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_multi_execute",
    description: "Compatibility wrapper that routes to CompanySlackRuntime.",
    tags: <String>["agent"],
    aliases: <String>[
      "defaults.agent.multi.execute",
      "defaults.agent.multi_execute",
      "defaultspack.agent.multi.execute",
      "defaultspack.agent.multi_execute"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_multi_message",
    description: "Post a compatibility message to CompanySlackRuntime.",
    tags: <String>["agent"],
    aliases: <String>[
      "defaults.agent.multi.message",
      "defaults.agent.multi_message",
      "defaultspack.agent.multi.message",
      "defaultspack.agent.multi_message"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_multi_status",
    description: "Read compatibility CompanySlackRuntime thread status.",
    tags: <String>["agent"],
    aliases: <String>[
      "defaults.agent.multi.status",
      "defaults.agent.multi_status",
      "defaultspack.agent.multi.status",
      "defaultspack.agent.multi_status"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_ask",
    description: "Ask an agent organization.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.ask",
      "defaults.agent.org_ask",
      "defaultspack.agent.org.ask",
      "defaultspack.agent.org_ask"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_create",
    description: "Create an agent organization.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.create",
      "defaults.agent.org_create",
      "defaultspack.agent.org.create",
      "defaultspack.agent.org_create"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_delete",
    description: "Delete an agent organization.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.delete",
      "defaults.agent.org_delete",
      "defaultspack.agent.org.delete",
      "defaultspack.agent.org_delete"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_get",
    description: "Get an agent organization.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.get",
      "defaults.agent.org_get",
      "defaultspack.agent.org.get",
      "defaultspack.agent.org_get"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_instruct",
    description: "Instruct an agent organization.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.instruct",
      "defaults.agent.org_instruct",
      "defaultspack.agent.org.instruct",
      "defaultspack.agent.org_instruct"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_list",
    description: "List agent organizations.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.list",
      "defaults.agent.org_list",
      "defaultspack.agent.org.list",
      "defaultspack.agent.org_list"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_member_add",
    description: "Add an agent organization member.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.member.add",
      "defaults.agent.org_member_add",
      "defaultspack.agent.org.member.add",
      "defaultspack.agent.org_member_add"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_member_remove",
    description: "Remove an agent organization member.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.member.remove",
      "defaults.agent.org_member_remove",
      "defaultspack.agent.org.member.remove",
      "defaultspack.agent.org_member_remove"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_report",
    description: "Request an agent organization report.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.report",
      "defaults.agent.org_report",
      "defaultspack.agent.org.report",
      "defaultspack.agent.org_report"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_role_define",
    description: "Define an agent organization role.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.role.define",
      "defaults.agent.org_role_define",
      "defaultspack.agent.org.role.define",
      "defaultspack.agent.org_role_define"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_roles_list",
    description: "List agent organization roles.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.roles.list",
      "defaults.agent.org_roles_list",
      "defaultspack.agent.org.roles.list",
      "defaultspack.agent.org_roles_list"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_org_transfer_context",
    description: "Transfer context to an agent organization.",
    tags: <String>["agent", "org"],
    aliases: <String>[
      "defaults.agent.org.transfer.context",
      "defaults.agent.org_transfer_context",
      "defaultspack.agent.org.transfer.context",
      "defaultspack.agent.org_transfer_context"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_pause",
    description: "Pause an agent.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.pause", "defaultspack.agent.pause"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_plan",
    description: "Create an agent plan.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.plan", "defaultspack.agent.plan"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_progress",
    description: "Get agent progress.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.progress", "defaultspack.agent.progress"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_queue_get",
    description: "Get the agent queue.",
    tags: <String>["agent"],
    aliases: <String>[
      "defaults.agent.queue.get",
      "defaults.agent.queue_get",
      "defaultspack.agent.queue.get",
      "defaultspack.agent.queue_get"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_queue_update",
    description: "Update the agent queue.",
    tags: <String>["agent"],
    aliases: <String>[
      "defaults.agent.queue.update",
      "defaults.agent.queue_update",
      "defaultspack.agent.queue.update",
      "defaultspack.agent.queue_update"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_redirect",
    description: "Redirect an agent.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.redirect", "defaultspack.agent.redirect"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_reject",
    description: "Reject an agent action.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.reject", "defaultspack.agent.reject"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_resume",
    description: "Resume an agent.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.resume", "defaultspack.agent.resume"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_run_subagent",
    description:
        "Compatibility alias for utility model routing or delegated runs.",
    tags: <String>["agent"],
    aliases: <String>[
      "defaults.agent.run.subagent",
      "defaults.agent.run_subagent",
      "defaultspack.agent.run.subagent",
      "defaultspack.agent.run_subagent"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_schedule_create",
    description: "Create an agent schedule.",
    tags: <String>["agent", "scheduler"],
    aliases: <String>[
      "defaults.agent.schedule.create",
      "defaults.agent.schedule_create",
      "defaultspack.agent.schedule.create",
      "defaultspack.agent.schedule_create"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_schedule_delete",
    description: "Delete an agent schedule.",
    tags: <String>["agent", "scheduler"],
    aliases: <String>[
      "defaults.agent.schedule.delete",
      "defaults.agent.schedule_delete",
      "defaultspack.agent.schedule.delete",
      "defaultspack.agent.schedule_delete"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_schedule_get",
    description: "Get an agent schedule.",
    tags: <String>["agent", "scheduler"],
    aliases: <String>[
      "defaults.agent.schedule.get",
      "defaults.agent.schedule_get",
      "defaultspack.agent.schedule.get",
      "defaultspack.agent.schedule_get"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_schedule_history",
    description: "Get history for an agent schedule.",
    tags: <String>["agent", "scheduler"],
    aliases: <String>[
      "defaults.agent.schedule.history",
      "defaults.agent.schedule_history",
      "defaultspack.agent.schedule.history",
      "defaultspack.agent.schedule_history"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_schedule_list",
    description: "List an agent schedule.",
    tags: <String>["agent", "scheduler"],
    aliases: <String>[
      "defaults.agent.schedule.list",
      "defaults.agent.schedule_list",
      "defaultspack.agent.schedule.list",
      "defaultspack.agent.schedule_list"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_schedule_pause",
    description: "Pause an agent schedule.",
    tags: <String>["agent", "scheduler"],
    aliases: <String>[
      "defaults.agent.schedule.pause",
      "defaults.agent.schedule_pause",
      "defaultspack.agent.schedule.pause",
      "defaultspack.agent.schedule_pause"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_schedule_resume",
    description: "Resume an agent schedule.",
    tags: <String>["agent", "scheduler"],
    aliases: <String>[
      "defaults.agent.schedule.resume",
      "defaults.agent.schedule_resume",
      "defaultspack.agent.schedule.resume",
      "defaultspack.agent.schedule_resume"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_schedule_trigger",
    description: "Trigger an agent schedule.",
    tags: <String>["agent", "scheduler"],
    aliases: <String>[
      "defaults.agent.schedule.trigger",
      "defaults.agent.schedule_trigger",
      "defaultspack.agent.schedule.trigger",
      "defaultspack.agent.schedule_trigger"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_schedule_update",
    description: "Update an agent schedule.",
    tags: <String>["agent", "scheduler"],
    aliases: <String>[
      "defaults.agent.schedule.update",
      "defaults.agent.schedule_update",
      "defaultspack.agent.schedule.update",
      "defaultspack.agent.schedule_update"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_status",
    description: "Get agent execution status.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.status", "defaultspack.agent.status"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "agent_stepback",
    description: "Step an agent back.",
    tags: <String>["agent"],
    aliases: <String>["defaults.agent.stepback", "defaultspack.agent.stepback"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "browser_artifacts",
    description: "List persistent browser coding artifacts.",
    tags: <String>["browser", "tool"],
    aliases: <String>[
      "defaults.browser.artifacts",
      "defaultspack.browser.artifacts"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "browser_open_url",
    description: "Open a URL in a browser session.",
    tags: <String>["browser", "tool"],
    aliases: <String>[
      "defaults.browser.open.url",
      "defaults.browser.open_url",
      "defaultspack.browser.open.url",
      "defaultspack.browser.open_url"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "browser_screenshot",
    description: "Capture a browser screenshot.",
    tags: <String>["browser", "tool"],
    aliases: <String>[
      "defaults.browser.screenshot",
      "defaultspack.browser.screenshot"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "browser_session",
    description: "Open or inspect a browser session.",
    tags: <String>["browser", "tool"],
    aliases: <String>[
      "defaults.browser.session",
      "defaultspack.browser.session"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "computer_click",
    description: "Click with the computer controller.",
    tags: <String>["computer", "tool"],
    aliases: <String>["defaults.computer.click", "defaultspack.computer.click"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "computer_drag",
    description: "Drag with the computer controller.",
    tags: <String>["computer", "tool"],
    aliases: <String>["defaults.computer.drag", "defaultspack.computer.drag"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "computer_key",
    description: "Send a key with the computer controller.",
    tags: <String>["computer", "tool"],
    aliases: <String>["defaults.computer.key", "defaultspack.computer.key"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "computer_move",
    description: "Move the computer cursor.",
    tags: <String>["computer", "tool"],
    aliases: <String>["defaults.computer.move", "defaultspack.computer.move"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "computer_screenshot",
    description: "Capture a computer screenshot.",
    tags: <String>["computer", "tool"],
    aliases: <String>[
      "defaults.computer.screenshot",
      "defaultspack.computer.screenshot"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "computer_scroll",
    description: "Scroll with the computer controller.",
    tags: <String>["computer", "tool"],
    aliases: <String>[
      "defaults.computer.scroll",
      "defaultspack.computer.scroll"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "computer_type",
    description: "Type with the computer controller.",
    tags: <String>["computer", "tool"],
    aliases: <String>["defaults.computer.type", "defaultspack.computer.type"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_calculator",
    description: "Run the default calculator tool.",
    tags: <String>["math", "tool"],
    aliases: <String>[
      "defaults.tool.calculator",
      "defaultspack.tool.calculator"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_consent_check",
    description: "Check tool consent.",
    tags: <String>["tool"],
    aliases: <String>[
      "defaults.tool.consent.check",
      "defaults.tool.consent_check",
      "defaultspack.tool.consent.check",
      "defaultspack.tool.consent_check"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_consent_confirm",
    description: "Confirm tool consent.",
    tags: <String>["tool"],
    aliases: <String>[
      "defaults.tool.consent.confirm",
      "defaults.tool.consent_confirm",
      "defaultspack.tool.consent.confirm",
      "defaultspack.tool.consent_confirm"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_create",
    description: "Create a dynamic tool.",
    tags: <String>["tool"],
    aliases: <String>["defaults.tool.create", "defaultspack.tool.create"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_delete",
    description: "Delete a dynamic tool.",
    tags: <String>["tool"],
    aliases: <String>["defaults.tool.delete", "defaultspack.tool.delete"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_export",
    description: "Export a dynamic tool.",
    tags: <String>["tool"],
    aliases: <String>["defaults.tool.export", "defaultspack.tool.export"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_file_reader",
    description: "Run the default file reader tool.",
    tags: <String>["file", "tool"],
    aliases: <String>[
      "defaults.tool.file.reader",
      "defaults.tool.file_reader",
      "defaultspack.tool.file.reader",
      "defaultspack.tool.file_reader"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "properties": <String, dynamic>{
        "path": <String, dynamic>{"type": "string"},
        "start_line": <String, dynamic>{"type": "integer", "minimum": 1},
        "end_line": <String, dynamic>{"type": "integer", "minimum": 1},
        "max_chars": <String, dynamic>{
          "type": "integer",
          "minimum": 1,
          "description": "Optional output character budget for compact reads."
        },
        "max_tokens": <String, dynamic>{
          "type": "integer",
          "minimum": 1,
          "description":
              "Optional approximate output token budget for compact reads."
        }
      },
      "required": <dynamic>["path"],
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_invoke",
    description: "Invoke a registered tool.",
    tags: <String>["tool"],
    aliases: <String>["defaults.tool.invoke", "defaultspack.tool.invoke"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_list",
    description: "List registered tools.",
    tags: <String>["tool"],
    aliases: <String>["defaults.tool.list", "defaultspack.tool.list"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_mcp_connect",
    description: "Connect an MCP server.",
    tags: <String>["tool"],
    aliases: <String>[
      "defaults.tool.mcp.connect",
      "defaults.tool.mcp_connect",
      "defaultspack.tool.mcp.connect",
      "defaultspack.tool.mcp_connect"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_mcp_list",
    description: "List MCP servers.",
    tags: <String>["tool"],
    aliases: <String>[
      "defaults.tool.mcp.list",
      "defaults.tool.mcp_list",
      "defaultspack.tool.mcp.list",
      "defaultspack.tool.mcp_list"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_mcp_registry",
    description: "Manage registered MCP servers.",
    tags: <String>["tool"],
    aliases: <String>[
      "defaults.tool.mcp.registry",
      "defaults.tool.mcp_registry",
      "defaultspack.tool.mcp.registry",
      "defaultspack.tool.mcp_registry"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_names",
    description: "List registered tool names only.",
    tags: <String>["tool"],
    aliases: <String>["defaults.tool.names", "defaultspack.tool.names"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_reddit_search",
    description: "Run the default reddit search tool.",
    tags: <String>["research", "tool"],
    aliases: <String>[
      "defaults.tool.reddit.search",
      "defaults.tool.reddit_search",
      "defaultspack.tool.reddit.search",
      "defaultspack.tool.reddit_search"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_schema",
    description: "Get a registered tool schema.",
    tags: <String>["tool"],
    aliases: <String>["defaults.tool.schema", "defaultspack.tool.schema"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_subagent",
    description: "Run the default delegation tool.",
    tags: <String>["agent", "tool"],
    aliases: <String>["defaults.tool.subagent", "defaultspack.tool.subagent"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_task_board",
    description:
        "Create and update Kanban workspace task cards from the Task Board tool.",
    tags: <String>["planning", "task_board", "tool"],
    aliases: <String>[
      "defaults.tool.task_board",
      "defaultspack.tool.task_board"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_task_board_agent_session",
    description:
        "Link Kanban-backed task board cards to defaultspack coding agent sessions.",
    tags: <String>["agent", "planning", "task_board", "tool"],
    aliases: <String>[
      "defaults.tool.task_board.agent.session",
      "defaults.tool.task_board_agent_session",
      "defaultspack.tool.task_board.agent.session",
      "defaultspack.tool.task_board_agent_session"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_todo",
    description: "Run the default todo tool.",
    tags: <String>["planning", "tool"],
    aliases: <String>["defaults.tool.todo", "defaultspack.tool.todo"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_update",
    description: "Update a dynamic tool.",
    tags: <String>["tool"],
    aliases: <String>["defaults.tool.update", "defaultspack.tool.update"],
    inputSchema: <String, dynamic>{
      "type": "object",
      "additionalProperties": true
    },
  ),
  DefaultspackToolAgentManifestEntry(
    id: "tool_web_search",
    description: "Run the default web search tool.",
    tags: <String>["research", "tool"],
    aliases: <String>[
      "defaults.tool.web.search",
      "defaults.tool.web_search",
      "defaultspack.tool.web.search",
      "defaultspack.tool.web_search"
    ],
    inputSchema: <String, dynamic>{
      "type": "object",
      "properties": <String, dynamic>{
        "query": <String, dynamic>{"type": "string"},
        "limit": <String, dynamic>{
          "type": "integer",
          "minimum": 1,
          "maximum": 20
        },
        "allow_network": <String, dynamic>{"type": "boolean"},
        "domains": <String, dynamic>{
          "oneOf": <dynamic>[
            <String, dynamic>{
              "type": "array",
              "items": <String, dynamic>{"type": "string"}
            },
            <String, dynamic>{"type": "string"}
          ]
        },
        "official_only": <String, dynamic>{"type": "boolean"},
        "fetch_pages": <String, dynamic>{"type": "boolean"},
        "max_chars": <String, dynamic>{
          "type": "integer",
          "minimum": 1,
          "description": "Optional character budget for source excerpts."
        },
        "max_tokens": <String, dynamic>{
          "type": "integer",
          "minimum": 1,
          "description":
              "Optional approximate token budget for source excerpts."
        }
      },
      "required": <dynamic>["query"],
      "additionalProperties": true
    },
  ),
];
