
# flow/00_core.flow.yaml
# 基盤初期化（公式・ドメイン非依存）

flow_version: "2.0"
metadata:
  id: "core"
  priority: 0
  description: "基盤システムの初期化"

defaults:
  fail_soft: true
  on_missing_handler: "skip"

pipelines:
  startup:
    # マウントポイント初期化
    - id: "core.mounts"
      description: "ファイルシステムマウントの初期化"
      run:
        handler: "kernel:mounts.init"
        args:
          mounts_file: "user_data/mounts.json"
      on_error:
        action: "continue"

    # Pack/Component レジストリ読み込み
    - id: "core.registry"
      description: "ecosystem/配下の全Packを読み込み"
      run:
        handler: "kernel:registry.load"
        args:
          ecosystem_dir: "ecosystem"
      on_error:
        action: "abort"

    # アクティブエコシステム設定読み込み
    - id: "core.active_ecosystem"
      description: "無効化設定等を読み込み"
      run:
        handler: "kernel:active_ecosystem.load"
        args:
          config_file: "user_data/active_ecosystem.json"
      on_error:
        action: "continue"
