pipelines:
  startup:
    - id: "startup.setup"
      run:
        handler: "component_phase:setup"
        args: {}
      optional: true
      on_error:
        action: "continue"
    - id: "startup.runtime_boot"
      run:
        handler: "component_phase:runtime_boot"
        args: {}
      optional: true
      on_error:
        action: "continue"
  message:
    - id: "message.context_assemble"
      run:
        handler: "kernel:context.assemble"
        args: {}
      optional: true
      on_error:
        action: "continue"
    - id: "message.invoke"
      run:
        handler: "kernel:delegate.call"
        args:
          interface_key: "message.handle"
      optional: false
      on_error:
        action: "continue"
    - id: "message.persist"
      run:
        handler: "kernel:persist"
        args:
          targets: ["history", "ui_history", "chat_config"]
      optional: true
      on_error:
        action: "continue"
    - id: "message.output"
      run:
        handler: "kernel:output"
        args:
          mode: "auto"
      optional: true
      on_error:
        action: "continue"
  message_stream:
    - id: "message_stream.context_assemble"
      run:
        handler: "kernel:context.assemble"
        args: {}
      optional: true
      on_error:
        action: "continue"
    - id: "message_stream.invoke"
      run:
        handler: "kernel:delegate.call"
        args:
          interface_key: "message.handle_stream"
      optional: false
      on_error:
        action: "continue"
    - id: "message_stream.persist"
      run:
        handler: "kernel:persist"
        args:
          targets: ["history", "ui_history", "chat_config"]
      optional: true
      on_error:
        action: "continue"
    - id: "message_stream.output"
      run:
        handler: "kernel:output"
        args:
          mode: "auto"
      optional: true
      on_error:
        action: "continue"
