flow_version: "1.0"
project:
  id: "rumi_ai"
  title: "Rumi AI OS (fallback)"
defaults:
  fail_soft: true
  on_missing_handler: "skip"
  diagnostics:
    enabled: true
  install_journal:
    enabled: true
    dir: "user_data/settings/ecosystem/install_journal"
pipelines:
  startup:
    - id: "startup.mounts"
      run:
        handler: "kernel:mounts.init"
        args:
          mounts_file: "user_data/mounts.json"
    - id: "startup.registry"
      run:
        handler: "kernel:registry.load"
        args:
          ecosystem_dir: "ecosystem"
    - id: "startup.active_ecosystem"
      run:
        handler: "kernel:active_ecosystem.load"
        args:
          config_file: "user_data/active_ecosystem.json"
    - id: "startup.dependency"
      run:
        handler: "component_phase:dependency"
        args: {}
      optional: true
      on_error:
        action: "continue"
    - id: "startup.setup"
      run:
        handler: "component_phase:setup"
        args: {}
      optional: true
      on_error:
        action: "continue"
    - id: "startup.services_ready"
      run:
        handler: "kernel:interfaces.publish"
        args: {}
      optional: true
      on_error:
        action: "continue"
  message: []
  message_stream: []
