from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


PACK_ROOT = Path(__file__).resolve().parents[1]
RUMI_ROOT = PACK_ROOT.parents[1]
REGISTRY_PATH = RUMI_ROOT / "core_runtime" / "host_permissions" / "default_registry.json"
FUNCTIONS_ROOT = PACK_ROOT / "functions"

HOST_FUNCTION_ID_OVERRIDES = {
    "host.accessibility.read": "host_accessibility_snapshot",
    "host.accessibility.mutate": "host_accessibility_action",
    "host.file.read_user_selected": "host_file_read_selected",
    "host.file.write_user_selected": "host_file_write_selected",
}

MAIN_TEMPLATE = '''# @generated by scripts/generate_host_mediator_functions.py
# Source: core_runtime/host_permissions/default_registry.json
# Do not edit by hand; update the registry/generator and rerun with --write.
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _host_mediator import run_host_mediator


def run(context, args):
    return run_host_mediator(
        context,
        args,
        function_id="{function_id}",
        operation="{operation}",
        stream_allowed={stream_allowed},
    )
'''


def host_permission_registry() -> dict[str, dict]:
    return json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))


def host_function_id_for_operation(operation: str) -> str:
    return HOST_FUNCTION_ID_OVERRIDES.get(operation, operation.replace(".", "_"))


def expected_host_mediator_functions(registry: dict[str, dict] | None = None) -> dict[str, str]:
    source = registry if registry is not None else host_permission_registry()
    return {
        host_function_id_for_operation(operation): operation
        for operation, definition in source.items()
        if definition.get("broker_runner_implemented") is True
    }


def render_host_mediator_main(function_id: str, operation: str, stream_allowed: bool) -> str:
    return MAIN_TEMPLATE.format(
        function_id=function_id,
        operation=operation,
        stream_allowed=stream_allowed,
    )


def write_generated_files() -> None:
    registry = host_permission_registry()
    for function_id, operation in expected_host_mediator_functions(registry).items():
        function_dir = FUNCTIONS_ROOT / function_id
        function_dir.mkdir(parents=True, exist_ok=True)
        (function_dir / "main.py").write_text(
            render_host_mediator_main(
                function_id,
                operation,
                bool(registry[operation].get("stream_allowed")),
            ),
            encoding="utf-8",
        )


def check_generated_files() -> list[str]:
    registry = host_permission_registry()
    mismatches: list[str] = []
    for function_id, operation in expected_host_mediator_functions(registry).items():
        main_path = FUNCTIONS_ROOT / function_id / "main.py"
        expected = render_host_mediator_main(
            function_id,
            operation,
            bool(registry[operation].get("stream_allowed")),
        )
        if not main_path.is_file():
            mismatches.append(f"missing generated wrapper: {main_path.relative_to(PACK_ROOT)}")
            continue
        actual = main_path.read_text(encoding="utf-8")
        if actual != expected:
            mismatches.append(f"stale generated wrapper: {main_path.relative_to(PACK_ROOT)}")
    return mismatches


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate or check rumi_host_capabilities_pack mediator wrappers."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="verify generated function main.py wrappers without rewriting files",
    )
    mode.add_argument(
        "--write",
        action="store_true",
        help="rewrite generated function main.py wrappers from the host permission registry",
    )
    args = parser.parse_args(argv)

    if args.write:
        write_generated_files()
        print(f"generated {len(expected_host_mediator_functions())} host mediator wrappers")
        return 0

    mismatches = check_generated_files()
    if mismatches:
        print("host mediator wrappers are stale; run with --write", file=sys.stderr)
        for mismatch in mismatches:
            print(f"- {mismatch}", file=sys.stderr)
        return 1
    print("host mediator wrappers match generated output")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
